version: '3.7'

services:
  newsrum:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/backend

    ports:
      - '8000:8000'

    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_DATABASE=newsrum
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PORT=3306
    
    ports:
      - '3306:3306'

    volumes:
      - .db:/var/lib/mysql
