# Generated by Django 3.2.10 on 2022-01-21 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gernes', '0001_initial'),
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='gerne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='gernes.gerne'),
        ),
    ]
