# Generated by Django 3.2.10 on 2022-01-14 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gernes', '0001_initial'),
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('H', 'Hidden'), ('P', 'Public')], max_length=32)),
                ('gerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='gernes.gerne')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='PostClick',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='posts.post')),
            ],
            options={
                'db_table': 'post_click',
            },
        ),
        migrations.CreateModel(
            name='WebPost',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='web_post', serialize=False, to='posts.post')),
                ('url', models.URLField()),
                ('image_url', models.URLField(blank=True)),
                ('author', models.CharField(blank=True, max_length=128)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='publishers.publisher')),
            ],
            options={
                'db_table': 'web_post',
            },
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_post', serialize=False, to='posts.post')),
                ('image', models.FileField(upload_to=posts.models.post_image_path)),
                ('markdown', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('H', 'Hidden')], max_length=64)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_post',
            },
        ),
    ]
