# Generated by Django 3.2.9 on 2021-12-13 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'gerne',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('image', models.FileField(upload_to=posts.models.post_image_path)),
                ('gerne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.gerne')),
            ],
            options={
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=128)),
                ('logo', models.FileField(upload_to=posts.models.publisher_logo_path)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='WebPost',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='web_post', serialize=False, to='posts.post', unique=True)),
                ('url', models.URLField()),
                ('author', models.CharField(max_length=128)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.publisher')),
            ],
            options={
                'db_table': 'web_post',
            },
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_post', serialize=False, to='posts.post', unique=True)),
                ('markdown', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('H', 'Hidden')], max_length=64)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_post',
            },
        ),
    ]
