# Generated by Django 3.2.10 on 2022-01-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpost',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
