# Generated by Django 3.2.9 on 2021-12-13 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_post', serialize=False, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='webpost',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='web_post', serialize=False, to='posts.post'),
        ),
    ]
