# Generated by Django 3.2.10 on 2022-01-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_webpost_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='status',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accept'), ('H', 'Hidden')], max_length=32),
        ),
    ]
