# Generated by Django 3.2.10 on 2022-01-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_webpost_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='postclick',
            name='is_recommended',
            field=models.IntegerField(default=0),
        ),
    ]
