# Generated by Django 4.0.1 on 2022-01-23 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecSys',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('in_used', models.IntegerField(default=1)),
                ('params', models.CharField(max_length=255)),
                ('test_hit_7', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rec_sys',
            },
        ),
        migrations.CreateModel(
            name='RecResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_hit', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_results', to='recommender.recsys')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rec_result',
            },
        ),
    ]
