# Generated by Django 4.0.1 on 2022-01-23 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recsys',
            name='in_used',
            field=models.IntegerField(default=0),
        ),
    ]
